export const reviewStyles = {
  card: {
    border: '1px solid #ccc',
    borderRadius: '8px',
    padding: '10px',
    boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
    backgroundColor: 'transparent',
  },
  reviewContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '20px',
    padding: '20px',
    margin: '0px auto',
    maxWidth: '1200px',
    backgroundColor: 'transparent',
  },
  photoContainer: {
    width: '50',
    height: '50',
    overflow: 'hidden',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '10px 10px',
  },
  photo: {
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'cover',
  },
  details: {
    marginTop: '10px',
  },
  tagsContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  tag: {
    padding: '5px 10px',
    color: 'white',
    backgroundColor: '#EC5630',
    fontSize: '14px',
  },
  likeButton: {
    width: '25px',
    height: '25px',
    padding: '13px',
    backgroundPosition: 'center',
    backgroundImage: 'url(/img/Liked.png)',
    border: 'none',
    cursor: 'pointer',
  },
  likeButtonActive: {
    width: '25px',
    height: '25px',
    padding: '13px',
    backgroundPosition: 'center',
    backgroundImage: 'url(/img/activeLiked.png)',
    border: 'none',
    cursor: 'pointer',
  },
  like: {
    fontSize: '15px',
    color: '#1B4345',
    cursor: 'pointer',
    marginLeft: '10px',
  },
  placeName: {
    marginTop: '10px',
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1B4345',
  },
  content: {
    marginTop: '5px',
    marginBottom: '5px',
    color: '#1B4345',
    fontSize: '14px',
  },
  writeButton: {
    width: '70px',
    height: '70px',
    position: 'fixed',
    bottom: '50px',
    right: '90px',
    cursor: 'pointer',
    borderRadius: '50%',
    backgroundColor: '#1B4345',
    padding: '5px',
  },
};
