export const reviewModalStyles = {
  overlay: {
    backgroundColor: 'rgba(1, 1, 1, 0.5)',
  },
  modal: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '620px',
    height: '600px',
    backgroundColor: '#F2F2EF',
    padding: '20px',
    border: '3px solid #1B4345',
    borderRadius: '5px',
    boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)',
    zIndex: '2000',
  },
  closeButton: {
    position: 'absolute',
    top: '30px',
    right: '30px',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#1B4345',
    fontSize: '30px',
    fontWeight: 'bold',
    zIndex: '1000',
  },
  profileContainer: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '15px',
  },
  profileImg: {
    width: '75px',
    height: '75px',
    borderRadius: '50%',
    marginRight: '10px',
  },
  profileInfo: {
    display: 'flex',
    flexDirection: 'column',
  },
  profileName: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1B4345',
  },
  date: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#1B4345',
  },
  contentContainer: {
    marginBottom: '15px',
  },
  placeName: {
    marginBottom: '10px',
    fontSize: '24px',
    fontWeight: 'bold',
    textDecoration: 'underline',
    color: '#1B4345',
  },
  content: {
    marginBottom: '10px',
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1B4345',
  },
  photosContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginTop: '70px',
  },
  photo: {
    width: '200px',
    height: '200px',
    objectFit: 'cover',
    borderRadius: '5px',
    marginBottom: '10px',
  },
  footer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  likeSection: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '10px',
  },
  likeButton: {
    width: '20px',
    height: '20px',
    backgroundSize: 'cover',
    backgroundImage: 'url(/img/Liked.png)',
    border: 'none',
    cursor: 'pointer',
  },
  likeButtonActive: {
    width: '20px',
    height: '20px',
    backgroundSize: 'cover',
    backgroundImage: 'url(/img/activeLiked.png)',
    border: 'none',
    cursor: 'pointer',
  },
  like: {
    marginLeft:'10px',
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#1B4345',
  },
  tags: {
    marginTop: '20px',
  },
  tagButton: {
    width: 'auto',
    height: 'auto',
    marginRight: '10px',
    padding: '5px 10px',
    border: '2px solid #1B4345',
    color: '#1B4345',
    fontWeight: 'bold',
    fontSize: '14px',
  },
  editSection: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '10px',
  },
  editButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#1B4345',
    position: 'absolute',
    bottom: '60px',
    right: '120px',
  },
  delButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#1B4345',
    position: 'absolute',
    bottom: '60px',
    right: '50px',
  },
};
