export const reviewModalStyles = {
  overlay: {
    backgroundColor: 'rgba(1, 1, 1, 0.5)',
  },
  modal: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '620px',
    height: '600px',
    backgroundColor: '#F2F2EF',
    padding: "20px",
    border: '3px solid #1B4345',
    borderRadius: "5px",
    boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)',
    zIndex: '1000',
  },
  closeButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#1B4345',
    position: 'absolute',
    fontSize: '30px',
    fontWeight: 'bold',
    top: '30px',
    right: '30px',
    zIndex: '1000',
  },
  profileContainer: {
    position: 'relative',
  },
  profileImg: {
    width: '75px',
    height: '75px',
    borderRadius: '50%',
    marginRight: '10px',
  },
  profileName: {
    position: 'absolute',
    top: '35%',
    marginLeft: '120px',
    transform: 'translate(-50%, -50%)',
    padding: '10px',
    color: '#1B4345',
    fontWeight: 'bold',
  },
  date: {
    position: 'absolute',
    top: '60%',
    marginLeft: '163px',
    transform: 'translate(-50%, -50%)',
    fontSize: '13px',
    color: '#1B4345',
    fontWeight: 'bold',
  },
  placeName: {
    width: '100%',
    padding: '10px',
    borderRadius: '5px',
    border: 'none',
    outline: 'none',
    marginTop: '15px',
    marginBottom: '10px',
    backgroundColor: 'transparent',
    color: '#1B4345',
    fontSize: '30px',
    fontWeight: 'bold',
  },
  content: {
    color: '#1B4345',
    fontSize: '18px',
    fontWeight: 'bold',
  },
  photo: {
    width:'300px',
  },
  tags: {
    marginTop: '20px',
  },
  tagButton: {
    width: 'auto',
    height: 'auto',
    marginRight: '10px',
    padding: '5px 10px',
    border: '2px solid #1B4345',
    color: '#1B4345',
    fontWeight: 'bold',
    fontSize: '14px',
  },
  likeButtonActive: {
    color: '#1B4345',
    fontSize: '23px',
    border: 'none',
    background: 'none',
  },
  likeButton: {
    color: '#1B4345',
    border: 'none',
    fontSize: '20px',
    background: 'none',
  },
  like: {
    color: '#1B4345',
    fontWeight: 'bold',
    fontSize: '20px',
  },
  editButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#1B4345',
    position: 'absolute',
    bottom: '60px',
    right: '120px',
  },
  delButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#1B4345',
    position: 'absolute',
    bottom: '60px',
    right: '50px',
  },
};
