export const searchStyles = {
  container: {
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  inputContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '10px',
  },
  input: {
    padding: '10px',
    fontSize: '16px',
    width: '550px',
    border: 'none',
    outline: 'none',
    textAlign: 'center',
    borderRadius: '5px',
  },
  button: {
    width: '90px',
    height: '38px',
    padding: '5px 20px',
    fontSize: '15px',
    cursor: 'pointer',
    color: '#FFFFFF',
    backgroundColor: '#1B4345',
    border: 'none',
    borderRadius: '5px',
    marginLeft: '10px',
  },
  tagContainer: {
    marginTop: '15px',
    justifyContent: 'center',
  },
  tagList: {
    display: 'flex',
    flexWrap: 'wrap',
    marginBottom: '10px',
    justifyContent: 'center',
  },
  tag: {
    padding: '5px 10px',
    fontSize: '14px',
    fontWeight: 'bold',
    backgroundColor: 'transparent',
    border: '2px solid #1B4345',
    color: '#1B4345',
    cursor: 'pointer',
    margin: '5px',
    transition: 'background-color 0.3s, color 0.3s',
  },
};
