export const searchStyles = {
  
  searchContainer: {
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  inputContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '5px',
  },
  input: {
    padding: '15px',
    fontFamily: 'Freesentation',
    fontSize: '18px',
    width: '550px',
    border: 'none',
    outline: 'none',
    textAlign: 'center',
    borderRadius: '5px',
  },
  searchButton: {
    width: '90px',
    height: '45px',
    fontFamily: 'Freesentation',
    fontSize: '20px',
    cursor: 'pointer',
    color: '#FFFFFF',
    backgroundColor: '#1B4345',
    border: 'none',
    borderRadius: '5px',
  },
  searchTagContainer: {
    marginTop: '15px',
    justifyContent: 'center',
  },
  searchTagList: {
    display: 'flex',
    flexWrap: 'wrap',
    marginBottom: '10px',
    justifyContent: 'center',
  },
  searchTag: {
    padding: '4px 15px',
    fontSize: '14px',
    fontWeight: 'bold',
    backgroundColor: 'transparent',
    border: '2px solid #1B4345',
    color: '#1B4345',
    cursor: 'pointer',
    margin: '5px',
    transition: 'background-color 0.3s, color 0.3s',
  },
};
