export const writeModalStyles = {
  overlay: {
    backgroundColor: 'rgba(1, 1, 1, 0.5)',
  },
  modal: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '620px',
    height: '600px',
    backgroundColor: '#F2F2EF',
    padding: '50px',
    border: '3px solid #1B4345',
    borderRadius: '10px',
    boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)',
    zIndex: '1000',
  },
  closeButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#1B4345',
    position: 'absolute',
    fontSize: '30px',
    fontWeight: 'bold',
    top: '30px',
    right: '30px',
    zIndex: '1000',
  },
  profileContainer: {
    display: 'flex',
    alignItems: 'center',
    position: 'absolute',
    top: '30px',
    left: '30px',
    zIndex: '1000',
  },
  profileImg: {
    width: '75px',
    height: '75px',
    borderRadius: '50%',
    marginRight: '10px',
  },
  profileName: {
    fontSize: '20px',
    fontWeight: 'bold',
  },
  inputName: {
    width: '100%',
    padding: '10px',
    border: 'none',
    outline: 'none',
    marginTop: '75px',
    marginBottom: '10px',
    backgroundColor: 'transparent',
    color: '#1B4345',
    fontSize: '20px',
    fontWeight: 'bold',
    textDecoration: 'underline',
  },
  textarea: {
    width: '100%',
    height: '75px',
    padding: '10px',
    border: 'none',
    borderRadius: '5px',
    outline: 'none',
    backgroundColor: 'transparent',
    resize: 'none',
    color: '#000',
  },
  imgContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '20px',
  },
  addImg: {
    display: 'flex',
    width: '200px',
    height: '200px',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e0e0e0',
    cursor: 'pointer',
  },
  tagContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginTop:'15px',    
    marginBottom: '20px',
  },
  tagButton: {
    padding: '5px 10px',
    border:'2px solid #000000',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    transition: 'background-color 0.3s, color 0.3s',
  },
  selectedTagButton: {
    backgroundColor: '#000000',
    color: '#fff',
  },
  button: {
    color: '#FFFFFF',
    backgroundColor: '#1B4345',
    border: '2px none bold',
    borderRadius: "5px",
    position: 'absolute',
    fontSize: '15px',
    padding:'5px 15px',
    bottom: '30px',
    right: '40px',
  },
};
